ARG IRONLIB_IMAGE=ghcr.io/metal-toolbox/ironlib:v0.2.17
FROM $IRONLIB_IMAGE

COPY alloy /usr/sbin/alloy
RUN chmod +x /usr/sbin/alloy
COPY task.sh task.sh
RUN chmod +x ./task.sh

ENTRYPOINT ["./task.sh"]
