name: Release latest

on:
  push:
    branches:
      - main

jobs:
  # Push to latest
  container-push-latest-alloy-inband:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: alloy-inband
      tag: latest
      dockerfile_path: Dockerfile.inband

  container-push-latest-alloy:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: alloy
      tag: latest
      dockerfile_path: Dockerfile
